### ISSUE TITLE
HTML entities and other odd characters

### ISSUE THREAD

**Issue by yusijs** [lapwinglabs/x-ray#101]
I've recently started using x-ray, and it's an amazing tool! However, it causes me grief on special characters (such as ’ (MSWord formatted single quote) returning â€ and &nbsp; returning Â). 

Any suggestions on how I can look to improve this? 

Thanks!

**Comment by Kikobeats** [comment]
GOTO #144

**Comment by yusijs** [comment]
![](https://imgs.xkcd.com/comics/goto.png)

(https://xkcd.com/292/)
