### ISSUE TITLE
Throttle, Concurrency supported?

### ISSUE THREAD

**Issue by thinkloop** [lapwinglabs/x-ray#104]
Hello, the readme page says that throttle and concurrency are supported options, but it doesn't seem like they are implemented - am I missing something?

Thanks!

**Comment by matthewmueller** [comment]
You need to specify them on the base object:

```js
var x = Xray().concurrency(2)
x(...)(url, fn)
```

**Comment by thinkloop** [comment]
Awesome! It worked, thank u.
