### ISSUE TITLE
no result when a prepare function returns a number with value 0

### ISSUE THREAD

**Issue by FakeYou** [lapwinglabs/x-ray#11]
When a prepare function returns a number with a value of 0 the field will be entirely absent.

Consider this example:

```html
<div class="servers">
  <div class="server"> <h1>server 1</h1> <span class="users">10</span> </div>
  <div class="server"> <h1>server 2</h1> <span class="users">20</span> </div>
  <div class="server"> <h1>server 3</h1> <span class="users">0</span> </div> 
  <div class="server"> <h1>server 4</h1> <span class="users">15</span> </div>
</div>
```
```javascript
xray('http://localhost:3000')
  .prepare('parseInt', parseInt)
  .select([{
    $root: '.server',
    name: 'h1',
    users: '.users | parseInt'
  }]);
```

After running this the result is:
```json
[ { "name": "server 1", "users": 10 },
  { "name": "server 2", "users": 20 },
  { "name": "server 3" },
  { "name": "server 4", "users": 15 } ]
```

I would expect the result for `server 3` to include `"users": 0`.

Any idea what might be going on?

**Comment by MatthewMueller** [comment]
What's your `parseInt` implementation? First though is `0` will evaluate as `false` so it's being ignored, but I'm not really seeing it here: https://github.com/lapwinglabs/x-ray-select/blob/master/index.js#L72

**Comment by FakeYou** [comment]
I found the issue in https://github.com/lapwinglabs/x-ray-select/blob/master/index.js#L101. This `if` would trip over falsy values. I made a pull request where I changed this `if` to instead look if `found` is `undefined` or not.

**Comment by MatthewMueller** [comment]
fixed and published, thanks for the investigative work!
