### ISSUE TITLE
How to get to data not in html elements, but in javascript for instance? 

### ISSUE THREAD

**Issue by gebrits** [lapwinglabs/x-ray#110]
As an example I'm trying to get latitude/longitude which are available in a json-blob in the source-code. 

How would I get to this?

**Comment by mikemaccana** [comment]
xray has a driver for phantomjs, which evaluates JavaScript, but the xray docs don't seem to show how this is exposed to xray users.

**Comment by gebrits** [comment]
implemented this by simply having: 

```javascript
wantSomeHtmlSnippet: function(el, cb){
  var html  = el.html(); 
  var snippet = ... //now do some string manipulation 
  return cb(undefined, snippet)
}
```
