### ISSUE TITLE
tag only returns the 1st entry of it. 

### ISSUE THREAD

**Issue by IoDmitri** [lapwinglabs/x-ray#114]
The following code:
`` x('http://www.google.com','a')(function(err,obj){
  console.log(obj);
})``  will only return me a single element, whilst the actual site has multiple 'a' tags. This is a sudden issue that appeared for me, before it would grab all the a tags.

**Comment by Kikobeats** [comment]
@matthewmueller Just as example, add here a `question` label and a comment about how to do it could be very useful for the rest of the users :-)

I can help you in about this point, contact with me!
