### ISSUE TITLE
Crawling problem

### ISSUE THREAD

**Issue by ibeerepoot** [lapwinglabs/x-ray#129]
This works:

x('http://www.funda.nl/koop/verkocht/leiden/huis-85057888-paviljoenshof-8/', '.transaction-data', [{
&nbsp;&nbsp;start: '.transaction-date:nth-of-type(1) strong',
&nbsp;&nbsp;total: '.transaction-date:nth-of-type(3) strong',
&nbsp;&nbsp;end: '.transaction-date:nth-of-type(5) strong',
}])
	.write('json/testje.json')

So why doesn't this work:

x('http://www.funda.nl/koop/verkocht/heel-nederland/' + vanm2 + '-' + totm2 + '-woonopp/' + soort + '/', '.object-list li', [{
&nbsp;&nbsp;&nbsp;&nbsp;adres: 'a.object-street',
&nbsp;&nbsp;&nbsp;&nbsp;postcode: '.properties-list:nth-of-type(1)',
&nbsp;&nbsp;&nbsp;&nbsp;vraagprijs: '.price',
&nbsp;&nbsp;&nbsp;&nbsp;link: 'a.object-street@href',
&nbsp;&nbsp;&nbsp;&nbsp;start: x('a.object-street@href', '.transaction-date:nth-of-type(1) strong'),
&nbsp;&nbsp;&nbsp;&nbsp;total: x('a.object-street@href', '.transaction-date:nth-of-type(3) strong'),
&nbsp;&nbsp;&nbsp;&nbsp;end: x('a.object-street@href', '.transaction-date:nth-of-type(5) strong'),
&nbsp;&nbsp;}])
&nbsp;&nbsp;&nbsp;&nbsp;.paginate('.next@href')	
&nbsp;&nbsp;&nbsp;&nbsp;.write('json/verkocht/' + soort + '/' + soort + vanm2 + totm2 + '.json')

Start, total and end aren't returned in the second example. I read there are some crawling problems, so maybe this is one. Is there a solution for yet? Can I work around it in some way? Thanks in advance!

**Comment by OllieJennings** [comment]
Nested crawling is broken: #111
