### ISSUE TITLE
Crawling to another site

### ISSUE THREAD

**Issue by umpirsky** [lapwinglabs/x-ray#130]
Here is my snippet:

```javascript
var Xray = require('x-ray');
var x = Xray();

x('https://en.wikipedia.org/wiki/Main_Page', {
  title: 'title',
  subtitle: x('li#n-featuredcontent a@href', 'title')
})(function(err, obj) {
    console.log(obj);
})
```

Expected:

```
{ title: 'Wikipedia, the free encyclopedia', subtitle: 'Portal:Featured content - Wikipedia, the free encyclopedia' }
```

Actual:

```
{ title: 'Wikipedia, the free encyclopedia' }
```

Example from [readme](https://github.com/lapwinglabs/x-ray#crawling-to-another-site) returns: 

```
{ main: 'Google' }
```

as well, while:

```
{
    main: 'Google',
    image: 'Google Images'
}
```

is expected.

**Comment by ibeerepoot** [comment]
I have exactly the same problem, crawling to another site returns nothing. I'm thinking of saving the urls you get and then crawl all those pages, like so:

// loop through all new urls
x('url[i]', 'title');

But I'm still hoping to get a prettier solution from x-ray.

**Comment by OllieJennings** [comment]
mentioned in #111
