### ISSUE TITLE
Sanitize/Modify data before returning (middleware of sorts)?

### ISSUE THREAD

**Issue by ishan-marikar** [lapwinglabs/x-ray#140]
I'm writing a simple crawler that extracts information off of a yellow pages site in our country, and I'm having trouble trying to sanitize or modify the data before it is sent back to crawler.

Currently what I have is 

```js
x(URL, '.jd-table.jd-item', [{
  name: 'div.jd-itemTtile',
  telephone: 'span.jd-fields-li-value.val-horizontal',
  address: 'div.jd-itemAddress' // Field that needs to be sanitized
}])(function(error, response) {
  if (error) throw error;
  console.log(response);
});
```

The address field returns something like:
```
\r\n\r\n\n                            Address: 123, Mock Street, Earth                                         
 ```

Is there any sort of way where I can run this on the string before it is sent to the response:
address.replace(/(\r\n|\n|\r)/gm,'').replace(/Address/gi,'').trim();

I hope this makes sense. Thank you.

**Comment by gebrits** [comment]
afaik there isn't.  However, nothing is stopping you from writing a couple
of middleware-like functions yourself to parse the output

**Comment by ishan-marikar** [comment]
Thank you, @gebrits.
I'm having a bit of difficulty trying to find the documentation for x-ray.
Would you be so kind enough to let me know how I could write middleware-like functions in x-ray?

**Comment by gebrits** [comment]
Didn't mean to confuse you. X-ray doesn't provide you anything to that end.
I just meant that you could write some helper functions for sanitization
and include them in your flow when needed.

Something like:

var transformers = {
cleanupWhitespace: function(response){
//your cleanup code here
return cleanupWhitespace;
}
}

x(URL, '.jd-table.jd-item', [{
  name: 'div.jd-itemTtile',
  telephone: 'span.jd-fields-li-value.val-horizontal',
  address: 'div.jd-itemAddress' // Field that needs to be sanitized
}])(function(error, response) {
  if (error) throw error;

  response = transformers.cleanupWhitespace(response);

  console.log(response);
});

**Comment by klmdb** [comment]
Try something like this:



		  address: function($, cb){

			var address      = $.find('div.jd-itemAddress').replace(/(\r\n|\n|\r)/gm,'').replace(/Address/gi,'').trim();

		  	cb(null, address);
		  },

**Comment by Kikobeats** [comment]
This have more sense with filters, check this PR: https://github.com/lapwinglabs/x-ray/pull/145

I'm waiting that the author of the PR update it and fix tests
