### ISSUE TITLE
A way to get $root attributes

### ISSUE THREAD

**Issue by olivierlesnicki** [lapwinglabs/x-ray#15]
I'd like to extract the [href] of the root element (item) in a property called link:
```
$root: '.item',
link: '[href]'
```
What is the correct syntax?

**Comment by MatthewMueller** [comment]
It should work work if your html looks something like:

```html
<div class=".item">
  <a href="...">...</a>
</div>
```

**Comment by olivierlesnicki** [comment]
Mine looks something like this actually:
```
<a class="item" href="..."></a>
```

**Comment by MatthewMueller** [comment]
Then you should be able to do:

```json
{
  "link": ".item[href]"
}
```

depending on your structure

**Comment by olivierlesnicki** [comment]
Structure is:
```html
<div class="item-list">
  <h1>Title for the list of items</h1>
  <div class="item" href="link-for-first-item">
    <h2>Title for the first item</h2>
  </div>
  ...
  <div class="item" href="link-for-nth-item">
    <h2>Title for the nth item</h2>
  </div>
</div>
```

And I'm using this:
```js
{
  $root: '.item-list',
  title: 'h1',
  items: [{
   $root: '.item',
   link: '<-- which selector am I meant to use here? -->'
   title: 'h2'
  }]
}
```
By the way this library is amazing!

**Comment by MatthewMueller** [comment]
Ah, this is trickier. I think we'll need to revisit `$root`a bit, because `$root` scopes for collections, but in your case you'd want to group your results.

**Comment by olivierlesnicki** [comment]
Raised PR https://github.com/lapwinglabs/x-ray-select/pull/5

**Comment by MatthewMueller** [comment]
*mind blown*. all the other tests pass right? can you explain this a bit more?

**Comment by olivierlesnicki** [comment]
All tests pass, I've also modified them to cover this scenario as well and just pushed them.

- I've changed the `rselector` so it would also match attribute selector without element selectors:
  - A match on `.item[href]` - returns `['item[href]', 'item', 'href']`
  - A match on `[href]` used to return `['item[href]', 'href]']`
  - A match on `[href]` now returns `['item[href]', undefined, 'href']`

- I've modified the `.findMany()` function so that it will skip the `.find()` against the root element and instead run `.attr()` against it.

**Comment by matthewmueller** [comment]
This was fixed with:

```js
x('http://google.com', 'a', {
   href: '@href'
})
```
