### ISSUE TITLE
Incorrect Header Check

### ISSUE THREAD

**Issue by iwanjunaid** [lapwinglabs/x-ray#154]
I try to scrape this page http://www.skysports.com/football/competitions/premier-league/table

but got following error:

> { [Error: incorrect header check] errno: -3, code: 'Z_DATA_ERROR', response: null }

**Comment by Kikobeats** [comment]
Please follow template to report an issue

**Comment by firasalmanna** [comment]
I am having the same problem, did you manage to fix it?

**Comment by firasalmanna** [comment]
Okay, I fixed the problem    

I am using `superagent` driver, so it seems the website I am using has some different encodings.    
This comment helped me fix it:    
https://github.com/visionmedia/superagent/issues/260#issuecomment-22608279
