### ISSUE TITLE
write function and stream

### ISSUE THREAD

**Issue by falkenlabs** [lapwinglabs/x-ray#16]
First of all thanks for your x-ray library it rocks !!
 
For a project i'm using the `xray.write()` function that return a `WritableStream` cause i need to parse a lot of web pages and return a very big json array (max 1 millions entries) and using the `xray.run()` flushed the memory quickly.
For this i want to use Koa.js to retrieve all the data, when i hit a specific url, something like this : 

```javascript
var xray = require('x-ray');
var match = {
    paginates: 'ul#paging li:nth-last-child(2) a[href]',
    links: [ '.list-lbc a:not(.alertsLink)[href]' ]
};

// this function return a very big json array...to the out.json file
var getLinks = function *getLinks(url) {
   return xray(url)
      .select(match.links)
      .paginate(match.paginates)
      .write('out.json');
};
```
Do you know how to pipe or redirect the writeable stream to `this.body`of koa.js ?

```javascript
// something like this, i need to hit the '/links' url of a dedicated server to retrieve 
// this very big json array.

app.get('/links', function *() {
   this.body = yield getLinks(url);
});
```

Thanks in advance.

**Comment by MatthewMueller** [comment]
Oh yah this is a nice use case. `this.body` takes a readable stream. 

So we can modify `xray.write()` with no arguments to return a readable stream so we could do something like:

```js
app.get('/links', function *() {
   this.body = return xray(url)
      .select(match.links)
      .paginate(match.paginates)
      .write();
});
```

**Comment by koalabz** [comment]
It would be perfect and even simpler :+1:

**Comment by MatthewMueller** [comment]
Will get to this soonish, accepting PRs though :-). I think using `through2` is the way to go if there are no arguments, to do the transform.

**Comment by matthewmueller** [comment]
This is now added :-)

**Comment by sagivf** [comment]
@matthewmueller @koalabz I was hopping you could assist me. I use `koa` and would like to use the `.stream()` in order to yield the value, but I would like to do some processing on the resulting json. I could wrap things up with promises and cllbacks but was wondering of there is any way to convert the stream to an object. (I don't have much experience with streams), any ideas? :+1: on x-ray rocks!

**Comment by Kikobeats** [comment]
@sagivf I'm not sure if I understand you but try this:

```
var stream = xray.stream()
stream.on('data', console.log)
```

**Comment by sagivf** [comment]
thanks @Kikobeats, but what I need is a way to convert the stream into an object. I can just use the x-ray without the stream and handle the callback to get the object, but i'm trying to see if there is a nicer way to integrate it with koa.

**Comment by sagivf** [comment]
Assigning it to `this.body` works by the way, but I can't manipulate and enrich the json that way.
