### ISSUE TITLE
Absolute URL doesn't work with every case

### ISSUE THREAD

**Issue by cbou** [lapwinglabs/x-ray#17]
When calling an url for example `http://example.com/contact.html` with links with `href` value being `legal.html`. The returned link is `http://example.com/contact.html/legal.html`.

I think it would be better to use a library like http://medialize.github.io/URI.js instead of doing such a complex stuff.

**Comment by cbou** [comment]
Another issue: when calling an `http` which is redirect to `https`, the absolute url ouputs a `http` url. A `https` url would be better.

**Comment by MatthewMueller** [comment]
yah, so we'll need the response url after redirects from superagent. I don't think a library is really that helpful because we'll still need to provide it with the appropriate information on what the response url is.
