### ISSUE TITLE
How to get followed url?

### ISSUE THREAD

**Issue by gabrielelanaro** [lapwinglabs/x-ray#176]
Through x-ray it's possible to follow a certain link for example by scraping anchors on the page.

I was wondering: is it possible to retrieve the URL of the page that was followed? Is there a selector that can allow that?

**Comment by Huvik** [comment]
You can have same selector for following and just saving href:
```javascript
{
    href: 'a@href'
    follow: x('a@href', {title: 'h1'})
}
```

**Comment by mcornella** [comment]
That's the right answer. @gabrielelanaro you can close this now.

**Comment by kanethal** [comment]
This works well for subsequent follows, but how can I get the first page? Is there an equivalent to document.URL?

**Comment by mcornella** [comment]
You should create a new issue with a detailed use case. I don't really understand what you mean with subsequent follows.

**Comment by kanethal** [comment]
I've adjusted my strategy to avoid this issue, but the use case originally
was:

I'm scraping a series of pages using the pagination feature. Each page
scrapes details in the following fashion:

let ScrapeTargets = {
URL : Get the current URL,
Title : 'title'
}

let startURL = 'http://somepage.com'

X(startURL, ScrapeTargets)
   .paginate('a@href')
   .write('out.json')

How do I capture the URL of the page currently under evaluation?
