### ISSUE TITLE
New and trying to understand selectors to find emails across different site structures

### ISSUE THREAD

**Issue by JephMarketing** [lapwinglabs/x-ray#177]
## My Issue
I am very new to x-ray, node, and scraping and want to learn how to only select emails from unstructured data.

My first project with x-ray is to build a scraper that pulls emails from sites that I pass into the program. Currently, I am only able to grab all 'a' elements and write them to an array with the href attributes. (As seen in the EggHead tutorial.) However, I know that in JQuery there are ways to grab all the a tags that also have the "mailto:" protocol. I believe that the JQuery would look something like this: 
`a[href^="mailto:"]`

I realize that this is probably very trivial and I apologize for that, but I still want to learn and need help to do so. Thank you in advance for your time! 

### My environment
I am using Node.js 4.4.3 (x86) 
npm 2.15.1 (default with node download) 

### Current Attempt: 
`xray('link','a[href="mailto:"]',
    [{
        email: ''
    }]

)

.write('results.json');`

**Comment by JBaczuk** [comment]
Did you ever figure this out?
