### ISSUE TITLE
Fix scraping without a $root

### ISSUE THREAD

**Issue by gpbmike** [lapwinglabs/x-ray#2]
Given the following page HTML...

```html
<a href="page1.html">Page 1</a>
<a href="page2.html">Page 2</a>
```

... how would I extract the link text and `href`s?

```javascript
xray('lots-of-links.com')
  .select([{
    $root: 'a',
    text: ??,
    href: ??
  }])
  .run(function (error, links) {
    // I would like an array on links
    // [
    //   { 
    //     text: 'Page 1',
    //     href: 'page1.html'
    //   },
    //   {
    //     ...
    //   }
    // ]
  });
```
I don't know how to reference the $root node. :(

**Comment by MatthewMueller** [comment]
In that case you wouldn't use the $root and just select `a` tags. $root is used to scope your selection within an element.

This should work:

```
xray('lots-of-links.com')
  .select([{
    text: 'a',
    href: 'a[href]'
  }])
  .run(function (error, links) {
    // I would like an array on links
    // [
    //   { 
    //     text: 'Page 1',
    //     href: 'page1.html'
    //   },
    //   {
    //     ...
    //   }
    // ]
  });
```

**Comment by gpbmike** [comment]
I run the following...

```javascript
var xray = require('x-ray');
xray('http://mat.io')
  .select([{
    text: 'a',
    href: 'a[href]'
  }])
  .run(function (error, array) {
    console.log(array);
  });
```

... and get ...

```
[ { text: 'Github', href: 'http://github.com/matthewmueller' } ]
```
... which is not what I would expect. I'm trying to get all of the links.

I'm sure I'm missing something simple. I'm running this in express if that makes a difference.

**Comment by MatthewMueller** [comment]
Ah, interesting. Looks like a bug, I'll take a look

**Comment by vraptorche** [comment]
Hi, 
I also have the problem described by @gpbmike - trying to select an array of elements but get back only array of one element - the first one. Is there any progress with this issue ?

Thanx 

~Emilk

**Comment by MatthewMueller** [comment]
latest x-ray should fix this. it now groups elements when you do not specify a `$root`, so you should be able to do:

```js
xray('lots-of-links.com')
  .select([{
    text: a,
    href: 'a[href]'
  }])
```

Let me know if you have any problems!
