### ISSUE TITLE
passing in an external Cheerio instance to x-ray

### ISSUE THREAD

**Issue by gebrits** [lapwinglabs/x-ray#22]
Is it possible to pass-in an external cheerio instance? e.g.: `$`. 
Use-case: I'n authenticating using Request + Cheerio (following this [tutorial](http://shrew.io/post/89337937049/scraping-websites-with-node-js-authentication)), since authentication using x-ray is not that easy (1). 

Noew I've done `var $ = cheerio.load(body);`, leaving me with the correct cheerio context after logging-in. It would be great if I could easily pass this cheerio context to x-ray so I could leverage `x-ray.select` etc. 

Is that possible? 

1): I've seen this [issue](https://github.com/lapwinglabs/x-ray/issues/5) with the rec to use phantomJS and try to authenticate through Nightmare. I didn't have much luck going in that direction. Besides it would be great not having to resort to this for performance reasons, having to build phantomJS on a system just for the need if authentication, etc.

**Comment by olivierlesnicki** [comment]
@gebrits you need a browser to interact with the page, store/set cookies, how would you do it without PhantomJS? Plus x-ray-phantom is an opt-in solution, you don't have to use it if you don't want to.

**Comment by gebrits** [comment]
@olivierlesnicki 

1. You don't need a browser to store/set cookies. It's just passing http headers/cookies
2. I don't need to 'interact' with a page. If with that you mean that the page should react to something like click-events. Instead I just need to scrape server-side rendered pages. (so no client-side/javascript generated code) The latter being an excellent use-case to use PhantomJS, but for a lot of other stuff it's overkill. 
3. I realize I don't have to use Phantom as a plugin to x-ray but atm it seems the advised workaround to authenticate. However, authentication (setting some headers, and remembering cookies) in essence has little to do with the reason to use PhantomJS. Or in other words, using PhantomJS purely for the reason to authenticate seems overkill.

**Comment by olivierlesnicki** [comment]
@gebrits OK I see your point there

**Comment by olivierlesnicki** [comment]
@gebrits You could create a plugin for it and register it with `.use(plugin)`.
The plugins have access to the `xray` instance and can overwrite the `xray.request` method which is used to access the page (you could set headers) and collect the HTML content.

**Comment by gebrits** [comment]
Ahh yes, that would be a good way. Thanks @olivierlesnicki

**Comment by olivierlesnicki** [comment]
Something along the lines of (don't copy/paste the code I've probably made 1,000 mistakes):
```js
var request = require('request');
var cheerio = require('cheerio');
var xray = require('x-ray');

function driver(credentials) {
  
  return function plugin(xray) {

    xray.request = function(url, fn) {
      request.post({
          uri: 'http://yourwebsite.com/login',
          headers: { 
            'content-type': 'application/x-www-form-urlencoded' 
          },
        body: require('querystring').stringify(credentials)
      }, function(err, res, body){

        if(err) return fn(err);

        request(url, function(err, res, body) {

          if(err) return fn(err);

          return fn(null, body);

        });
      });
    }

    return xray;

  }

}

xray('http://yourwebsite.com/login')
  .use(driver({
    username: 'kevin',
    password: 'secret'    
  }))
  .select()
```

**Comment by gebrits** [comment]
Thanks @olivierlesnicki , will give this a try soon. Looks good on the outset. Only thing that seems to be missing at a glance is needing to set `jar: true` to save cookies for subsequent requests. Will update with complete example once I get around to it. Thanks again.

**Comment by gebrits** [comment]
@olivierlesnicki works nicely! Here's the slightly altered snippet I'm using: 

   
        function driver(credentials, jar, isLoggedIn) {

         function reqFN(url, fn){
             request({
                url: url, 
                jar: jar,
              }, function(err, res, body) {
                if(err) return fn(err);
                return fn(null, body);
              });
          }

          return function plugin(xray) {
            xray.request = function(url, fn) {
              if(isLoggedIn(jar)){
                reqFN(url, fn);
              }else{
                request.post({
                    jar: jar,
                    followAllRedirects: true,
                    uri: 'https://mysite.com/login',
                    headers: { 
                      'content-type': 'application/x-www-form-urlencoded' 
                    },
                  body: require('querystring').stringify(credentials)
                }, function(err, res, body){
                  if(err) return fn(err);
                  reqFN(url, fn);
                });
              }
            };
            return xray;
          };
        }


        var myJar = request.jar();

        //'https://www.odesk.com/o/jobs/browse/'
        xray("https://mysite.com")
          .use(driver({ //These credentials should match the intput names on the login form
             username: 'username',
              password: 'password'
          }, myJar, function(jar){
            //A custom function to signal based on looking at the cookies when a user is logged in or not. 
            //This is used so we don't need to login for all subsequent requests.
            return (jar.getCookieString("https://mysite.com").indexOf("<loginneedle>") !== -1);
          }))

          .select([{
            //stuffz
          }])
          .paginate('.paginate')
          .limit(10)
          .write(process.stdout);

**Comment by MatthewMueller** [comment]
thanks @ol

**Comment by anasqadrei** [comment]
@gebrits Your code didn't work with me. It kept saying that xray `has no method 'use'` or `has no method 'select'`. Does it work with older versions of xray? Could you also add a valid website and all the `require` statements please.

**Comment by mindbits** [comment]
+1

**Comment by jasper-lyons** [comment]
It looks like the API has changed significantly since this was an acceptable solution, which has broken this solution. Perhaps we could open this issue again?

It would be useful if in the x-ray-crawler repo there were some example of how to use drivers with the newer, functional API?

I understand that @matthewmueller, you might not have the time to fix things but without examples, the ROI on having to grok your code before using the library is pretty terrible. It's a lot of effort for little gain.

**Comment by matthewmueller** [comment]
@jasper-lyons sorry for your frustration, turns out designing a scraping API that works on every website out there is a pretty difficult undertaking. There are more breaking changes on the horizon once this lands: https://github.com/segmentio/nightmare/issues/200. But we should be one step closer to our goal.

Often times looking at tests is a good place to find examples, including how to pass a cheerio instance in.

**Comment by heycalmdown** [comment]
It can be easily achieved with new APIs

```javascript
let superagent = require('superagent');
let Xray = require('x-ray');

logIntoYourSiteWith(agent).then(() => {
  let x = Xray().driver(driver(agent));
  x('http://somewhere', 'scope', [{}]);
});

function driver(opts) {
  return function http_driver(ctx, fn) {
    console.log(ctx.url);
    agent
      .get(ctx.url)
      .set(ctx.headers)
      .end(function(err, res) {
        if (err && !err.status) return fn(err)

        ctx.status = res.status
        ctx.set(res.headers)

        ctx.body = 'application/json' == ctx.type
          ? res.body
          : res.text

        // update the URL if there were redirects
        ctx.url = res.redirects.length
          ? res.redirects.pop()
          : ctx.url

        return fn(null, ctx)
      })
  }
}
```

**Comment by blakewest** [comment]
Hey, so I had this same problem. I was a bit confused, bug dig some digging. So to add some color to @heycalmdown 's answer... the function he posted is copied from the default driver that x-ray already uses. But if you want to pass some auth headers, for example, you'll have to tweak it slightly. You can do it like so...
```js
modules.export = driver
var superagent = require('superagent')

function driver(opts) {
  return function http_driver(ctx, fn) {
    console.log("Fetching...", ctx.url);
    superagent
      .get(ctx.url)
      .set(_.merge(ctx.headers, opts.headers))
      .end(function(err, res) {
        if (err && !err.status) return fn(err)

        ctx.status = res.status
        ctx.set(res.headers)

        ctx.body = 'application/json' == ctx.type
          ? res.body
          : res.text

        // update the URL if there were redirects
        ctx.url = res.redirects.length
          ? res.redirects.pop()
          : ctx.url

        return fn(null, ctx)
      })
  }
}

var cookies = {Cookie: cookieVal}
var driverWithAuth = driver({headers: cookies});
x = Xray().driver(driverWithAuth);
// Go about your day with xray.
x(yourUrl)
```
This worked for me.
