### ISSUE TITLE
Get <br/> from output

### ISSUE THREAD

**Issue by alexandre1985** [lapwinglabs/x-ray#229]
### \<br/\> tags disappear from output

I'm getting some \<p\> from a webpage with this command `x(page, '#myid', ['p'])...`. Sometimes the text that I want to show is separated by \<p\> and everything is fine.
But sometimes the text is separated by \<br/\> (or can even be \<br\> only) and I would want to split those \<br/\>.
The problem is that with my command it doesn't show any \<br/\> on the output (and those exist); so I can't split that string. Is there anyway to show the \<br/\> on the output ?

### Your environment

* version of node: v6.8.1
* version of npm: 3.10.8

### Steps to reproduce

```
var xray = require('x-ray');
var x = xray();
x('http://lifestyle.sapo.pt/astral/previsoes/miguel-de-sousa?signo=carneiro', '#semanal', ['p'])(function(err, data) {
  for (var i = 0; i < data.length; i++) { console.log(data[i]); }
});
```

### Expected behaviour

text\<br/\>text\<br/\>text\<br/\>text

### Actual behaviour
texttexttexttext

**Comment by tokhi** [comment]
You can use filters, its in the documentation.

```js
var Xray = require('x-ray');
var x = Xray({
  filters: {
    clean: function (value){
      value.replace('<br />', '');
       return value;
    }
  }
});
```
Then you can call it as below:

```js
x('http://mat.io', {
  content: 'content | clean'
})
```

**Comment by alexandre1985** [comment]
@tokhi you didn't understand it right. I don't want to remove the \<br/\> I want it to be shown! With xray like it is, it doesn't show the \<br\>'s...

**Comment by alexandre1985** [comment]
I'm making some progress. With `x(string, '#'+duracao, ['p@html'])` I'm able to show the \<br\> but the problem now is that the text isn't showing like utf-8.
For example:  `ã` is showing like `&#xE3;`

**Comment by tokhi** [comment]
Add this to your filter then you should be good:

```js
return  JSON.parse( JSON.stringify( value ) ); // This should be able to render the  ã
```

**Comment by alexandre1985** [comment]
Thank you @tokhi . It didn't work.
I was able to decode the numeric entities by adding the module 'entities'.
I didn't want a new dependency but now it's working

**Comment by tokhi** [comment]
gr8, plz don't forget to close the ticket if it is resolved.
