### ISSUE TITLE
Way to escape the $root-scope?

### ISSUE THREAD

**Issue by gebrits** [lapwinglabs/x-ray#23]
I'm using something like: 

    .select([{
      $root: '.oJobTile',
      id: ".oSaveLink [data-jobid]",
      title: '.oRowTitle a',
      link: '.oRowTitle a[href]',
    }])

And would like to include a property that's outside of the `$root`-scope. 
E.g.:

    .select([{
      $root: '.oJobTile',
      id: ".oSaveLink [data-jobid]",
      title: '.oRowTitle a',
      link: '.oRowTitle a[href]',
      curpage: 'body .curpage; //where body .curpage is outside of the $root scope. 
    }])

Is something like this possible?

**Comment by gebrits** [comment]
Done a quick hack in x-ray-select to make this work.

    function object_find_one($root, obj, formatters) {
      var $prevroot = $root;
      $root = obj.$root ? $root.find(obj.$root) : $root;
      var xray = this;
      var out = {};

      keys(obj).forEach(function(k) {
        var v = obj[k];

        var str = 'string' == typeof v ? string_find_one.call(xray, $root, v, formatters) : xray(v, v.$docRoot ? $root._root : $root);

        if (v.$flatten) {
          for (var prop in str) {
            str = str[prop];
            break;
          }
        }

        if (str !== undefined) out[k] = str;
      });

      return out;
    }


Format: 

      //escaping the $root-context and using the doc context instead, e.g.: 
      property_outside_root_context: {
        $docRoot: true, //escape the root context
        $flatten: true, //flatten the 
        prop: '.oPagination a:last-child[href]' //If $flatten is used, 'prop' may be anything, since value is squashed to 'property_outside_root_context'
      }

**Comment by MatthewMueller** [comment]
hmm, so this wouldn't work, right?

```js
.select({
  curpage: 'body .curpage',
  jobs: [{
    $root: '.oJobTile',
    id: ".oSaveLink [data-jobid]",
    title: '.oRowTitle a',
    link: '.oRowTitle a[href]',
  }]
})
```

I'd like to avoid imposing restrictions on how the data is structured, but I also don't want to introduce a method for everything. It's definitely a balance, I'll have to think about this one.

**Comment by olivierlesnicki** [comment]
I would agree with @MatthewMueller.
I think this specific use case doesn't call for a new methods.

**Comment by gebrits** [comment]
@MatthewMueller: I understand the need to strike a balance. And sure the suggested example works, if it's okay to lay the burden with the clients interpreting the results. 

However, I feel the general use-case to be able to escape the $root, go to the global scope set a new $root, etc. allows for composing all sorts of more complex json objects, with relatively little added code-complexity. 

Just my 2 cents of course :)

**Comment by MatthewMueller** [comment]
That's a good point. For me the hesitation stems from:

- The current proposal with 2 properties is too complex and not orthogonal
- I don't really like the naming `$root-escape` or `$flatten`.
- I'm wondering if we can do this generically, that'll make extending this stuff easier or not have to add it to core.

So it's a combination of the current proposal, aesthetics, and extensibility. I'm definitely open to your ideas though on those fronts.

**Comment by gebrits** [comment]
As far the orthogonal issue, how about something like this: 


			function object_find_one($root, obj, formatters) {
			  var $prevroot = $root;
			  $root = obj.$root ? $root.find(obj.$root) : $root;
			  var xray = this;
			  var out = {};

			  keys(obj).forEach(function(k) {
			    var v = obj[k];

			    var str = 'string' == typeof v ? string_find_one.call(xray, $root, v, formatters) : xray(v, v.$docRoot ? $root._root : $root);

			    if (v.$flatten) {
			      for (var prop in str) {
			        out[prop] = str[prop]; //no undefined here
			      }
			    } else {
			      if (str !== undefined) out[k] = str;
			    }
			  });

			  return out;
			}

This allows for all properties to be flattened, i.e.: 

1. using `$docRoot` without `$flatten` on object A results in an object A in the output, and all properties of object A: 
 - to be escaped from the root-scope.
2.  using `$flatten` without `$docRoot` on object A results in the properties of object A: 
 - to be flattened and set directly on the parent of A
3. using `$docRoot` and `$flatten` on object A results in the properties of object A: 
 - to be flattened and set directly on the parent of A
 - to be escaped from the root-scope.

Nr 2. above isn't useful on it's own though. Have to think this though.

**Comment by MatthewMueller** [comment]
Thought about this a bit more, I definitely think this needs to be addressed. Right now I'm thinking more along the lines of:

```js
xray.select([{
  page: 'title',
  $extend: {
    $root: '.item',
    title: '.title',
    description: '.description' 
  },
  email: 'footer .email' 
}])
```

What do you think? Might be missing a use case or over-simplifying.

Not

**Comment by gebrits** [comment]
Yeah that would work for the mentioned case. It's cleaner I like it.

However, the limitation is that $root can only become more specific (i.e.: work towards the leafs of the dom-tree), it can't get more generic.

Although I'm not entirely sure it limits the expressiveness per se, I'm pretty sure it limits the way you can both: 
* be expressive with defining which properties to fetch AND
* format your output JSON any way you like

**Comment by olivierlesnicki** [comment]
@gebrits I think it's not a big issue to limit people format their output JSON from the select method. Especially because @MatthewMueller is planning on introducing the `.format()`

**Comment by gebrits** [comment]
@olivierlesnicki, ah didn't know of the upcoming `.format()`. With that in place, I'm pretty sure there's no usecase missing from the format @MatthewMueller  proposed. 

As to the naming for `$extend`: perhaps `$item` or `$element` would be an idea? After all, the `$extend` property is used to define which items/elements/children ultimately end up in the array.

**Comment by MatthewMueller** [comment]
@olivierlesnicki that's a good point, we could just use formatters to handle this. 

They're actually available already: https://github.com/lapwinglabs/x-ray#xrayformatfunction-fn :-P

They are slightly limited at the moment, because they cannot be run before and after the stream is complete (so they cannot close HTML tags or RSS feeds) but for your purposes that shouldn't be a problem.

**Comment by matthewmueller** [comment]
Closing this, I think post-processing is the way to go.
