### ISSUE TITLE
Cannot use scope when crawling to another site

### ISSUE THREAD

**Issue by vincaslt** [lapwinglabs/x-ray#231]
I have been following the [crawling to another site](https://github.com/lapwinglabs/x-ray#crawling-to-another-site) example and came up with this configuration:

```
x(URL, '.level', [{
  title: '.level-title | trim',
  words: x('.level@href', '.thing', {
    word: '.col_a',
    meaning: '.col_b'
  })
}])
```

returns: 

```
[
  { title: 'Fuel Your Vocab: Planet Earth', words: [] },
  { title: 'Human Preferences', words: [] }
]
```

while this:

```
x(URL, '.level', [{
  title: '.level-title | trim',
  words: x('.level@href', {
    word: '.thing .col_a',
    meaning: '.thing .col_b'
  })
}])
```

works fine, but only returns one value in words array: 

```
[
  { title: 'Fuel Your Vocab: Planet Earth', words: { word: 'el norte', meaning: 'the north' } },
  { title: 'Human Preferences', words: { word: 'el libro policiaco', meaning: 'the crime book' } }
]
```

In the first case, I tried defining the scope for words (`.thing`) objects, so that I can select an array, the same way I did for `.level` objects, but somehow it does not work there, even though the conditions are pretty much the same.

**Comment by vincaslt** [comment]
Ok, so after fiddling a little, I've found a way to do what I want:

```
x(URL, '.level', [{
  title: '.level-title | trim',
  words: x('.level@href', x('.thing', [{
    word: '.col_a',
    meaning: '.col_b'
  }]))
}])
```

However, I still believe the first case should work...

**Comment by snipem** [comment]
I had the same problem. Your approach fixed it.
