### ISSUE TITLE
Support asynchronous format functions

### ISSUE THREAD

**Issue by olivierlesnicki** [lapwinglabs/x-ray#24]

**Comment by MatthewMueller** [comment]
hmm, can you provide a use case?

**Comment by olivierlesnicki** [comment]
I'm extracting articles from a website including image links. I'm trying to extract the dominant color from each image, so I download the image, process it with node-canvas and then augment my json object with that data.

I don't know if it's a good enough case to do it inside the format function. Currently I've solved it by having an additional loop once the .run function completes.

**Comment by MatthewMueller** [comment]
yah, i think this may make more sense post-crawl or as the crawler streams.

going to close for now, but open to the idea if there's another use case.
