### ISSUE TITLE
Remove HTTP request logic from the library

### ISSUE THREAD

**Issue by gajus** [lapwinglabs/x-ray#245]
> This is very subjective. No offence is meant to anyone.

`x-ray` is a great tool to extract data from an HTML document. However, the half-baked integration of the HTTP request logic makes this tool feel impure.

To quote Peter H. Salus:

> Write programs that do one thing and do it well.

What makes me say "half-baked"?

* It only supports HTTP GET requests. You can reconfigure the driver to do the next request using different configuration, such as in the example of the `request-x-ray`, but there is no way to set these attributes at the time of invoking `xray` instance. This makes configuring HTTP headers, cookie persistency, request method, request body, etc. configuration yucky.
* HTTP is fragile. A thorough scraper will implement domain specific error handling, retry logic, cache, etc. This requires low level access to the HTTP request making logic.
* Throttle, delay, concurrency, pagination, etc. all belong to the HTTP request handling layer.

In this respect, I really like the https://github.com/rla/dom-eee library by @rla. It only implements the extraction expression evaluation logic and leaves logic of retrieving the document to the underlying business logic.

Removing HTTP request layer would achieve the following benefits:

* It would make the package re-usable in different environments, e.g. `dom-eee` can run in the browser or PhantomJS making it easy to debug certain cases.
* It would make the code base smaller. Smaller code base is easier to maintain and contribute to.
* It would make the API simpler. The API could be made into synchronous. There is no need for callbacks or promises.

Just my 2 cents.

Thank you for the awesome library.

**Comment by gajus** [comment]
I have incorporated these ideas into https://github.com/gajus/surgeon.

**Comment by gebrits** [comment]
imho most (all?) request logic sits in the X-ray Driver, which can be
swapped out for something that tickles your fancy. This includes
get/post/whatever, cookie-persistence, redirect logic, retry logic, setting
headers, proxying, etc.

Since everyone will want something else for advanced cases, just providing
a way to overwrite the driver seems a clean separation of concerns.

just my 2c.

**Comment by gajus** [comment]
You might be right. Either way. My concerns have covered by using Surgeon.

Should someone else want to champion this issue, please re-open it.

**Comment by gebrits** [comment]
Always good top have other options.
