### ISSUE TITLE
Example not working for me

### ISSUE THREAD

**Issue by ivansabik** [lapwinglabs/x-ray#25]
The example provided ``` github-stars.js ``` is not working for me. I did:

- ```git clone https://github.com/lapwinglabs/x-ray.git```
- ```npm update```
- ```node examples/github-stars.js ```

What I get is an error:

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'array'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/xyz/Desktop/x-ray/examples/github-stars.js:6:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

Maybe it's my config, node version or something else related to my environment's setup?

**Comment by ivansabik** [comment]
After doing ```npm install array``` I get:

```
/home/xyz/Desktop/x-ray/examples/github-stars.js:63
  .key('repo', 'div > ul > li.repo-list-item.public.source > h3.repo-list-name
   ^
TypeError: Object #<Xray> has no method 'key'
    at Object.<anonymous> (/home/ivanrodriguez/Desktop/x-ray/examples/github-stars.js:63:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by MatthewMueller** [comment]
Ah, sorry. I thought I removed these. Their API is out of date. For now, I'd take a look at the readme for now :-/

**Comment by ivansabik** [comment]
Ok matt, great thx!

**Comment by YonathanB** [comment]
I've tried with that website as root: 
http://www.yad2.co.il/Nadlan/rent.php?City=%D7%99%D7%A8%D7%95%D7%A9%D7%9C%D7%99%D7%9D&Neighborhood=&HomeTypeID=11&fromRooms=1&untilRooms=&fromPrice=200&untilPrice=&PriceType=1&FromFloor=&ToFloor=&EnterDate=&Info=

He return me a empty array??

**Comment by ivansabik** [comment]
Yonathan, your problem is not related to the issue opened here so please next time open a new one to keep issue tracking cleaner and nicer for everyone :)

The website is not scraping friendly, it checks for cookies, if not present it wont' work. To reproduce please do the following:

With cookies (cookiesBlocked.htm):

```
curl -o cookiesBlocked.htm 'http://www.yad2.co.il/Nadlan/rent.php?City=%D7%99%D7%A8%D7%95%D7%A9%D7%9C%D7%99%D7%9D&Neighborhood=&HomeTypeID=11&fromRooms=1&untilRooms=&fromPrice=200&untilPrice=&PriceType=1&FromFloor=&ToFloor=&EnterDate=&Info=' -H 'Cookie: CLIENT_WIDTH_DIR=1848; MAIN_WIDTH_DIR=1848; PHPSESSID=o7ecn245iinpp73mngpc0ls654; SaveSearch_CustID=gfd2718967172; yad2upload=3523215370.20480.0000; sbtsck=jav; adOtr=47E6U; PRLST=Ve; UTGv2=h48c431fc86a69fb6668b2aad7f2e5913558; SPSI=3867462f594f445fc2fc6a3b79b8e34b; favorites_userid=ffi1722812173'
```

Without cookies (noCookies.htm):

```
curl -o noCookies.htm 'http://www.yad2.co.il/Nadlan/rent.php?City=%D7%99%D7%A8%D7%95%D7%A9%D7%9C%D7%99%D7%9D&Neighborhood=&HomeTypeID=11&fromRooms=1&untilRooms=&fromPrice=200&untilPrice=&PriceType=1&FromFloor=&ToFloor=&EnterDate=&Info='
```

Copied cURL from Chrome (curlChrome.htm):

```
curl -o curlChrome.htm 'http://www.yad2.co.il/Nadlan/rent.php?City=%D7%99%D7%A8%D7%95%D7%A9%D7%9C%D7%99%D7%9D&Neighborhood=&HomeTypeID=11&fromRooms=1&untilRooms=&fromPrice=200&untilPrice=&PriceType=1&FromFloor=&ToFloor=&EnterDate=&Info=' -H 'DNT: 1' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Cookie: CLIENT_WIDTH_DIR=1848; MAIN_WIDTH_DIR=1848; PHPSESSID=o7ecn245iinpp73mngpc0ls654; SaveSearch_CustID=gfd2718967172; yad2upload=3523215370.20480.0000; sbtsck=jav; adOtr=47E6U; favorites_userid=ffi1722812173; UTGv2=h48c431fc86a69fb6668b2aad7f2e5913558; SPSI=3867462f594f445fc2fc6a3b79b8e34b' -H 'Connection: keep-alive' --compressed
```

So to wrap up: Scraping your target site is explicitly stated as illegal and would be kind of hard to technically do it. They have also other advanced blocking mechanisms maybe IP, not sure which ones.
You could try using Cheerio or similar which actually supports custom headers or something that emulates a real browser, found this https://github.com/yaplas/webdriveerio haven't tried it though but still the other blocking mechanisms would still apply (requests from same IP, etc).

**Comment by MatthewMueller** [comment]
There's also: https://github.com/lapwinglabs/x-ray-phantom, which makes requests through PhantomJS so it's be as if you were visiting the page in a browser.

**Comment by ivansabik** [comment]
Wasn't aware of that one, so @YonathanB if you try with x-ray it should work!

**Comment by YonathanB** [comment]
Thanks a lot for your answers (even if I've posted in the wrong place).
I've tried using phantom but I get an error using it (not defined)

**Comment by MatthewMueller** [comment]
can you paste the output of the error?

**Comment by YonathanB** [comment]
/Users/yonathanbenitah/Projects/testScripts/x-ray/test.js:71
    .use(phantom())
         ^
ReferenceError: phantom is not defined
    at Object.<anonymous> (/Users/yonathanbenitah/Projects/testScripts/x-ray/test.js:71:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

AND I've just tried to run the example there:

xray('http://google.com')
    .use(phantom())
    .type('input', 'x-ray')
    .click('.search')
    .select([{
        $root: '.result',
        title: '.title',
        link: 'a[href]'
    }])
    .write('out.json');

**Comment by MatthewMueller** [comment]
you need to:

```
var phantom = require('x-ray-phantom')
```

**Comment by YonathanB** [comment]
Yes,
Thanks a lot. 
i thought it was include in the x-ray-phantom folder

**Comment by ivansabik** [comment]
Your're welcome! @MatthewMueller just tested out with phantom, :+1 :+1 :+1
Be sure to have all dependencies, in Ubuntu:

```
sudo apt-get install phantomjs
npm install x-ray
npm install x-ray-phantom
```

Then

```
var xray = require('x-ray');
var phantom = require('x-ray-phantom');

var URL = 'http://www.yad2.co.il/Nadlan/rent.php?City=%D7%99%D7%A8%D7%95%D7%A9%D7%9C%D7%99%D7%9D&Neighborhood=&HomeTypeID=11&fromRooms=1&untilRooms=&fromPrice=200&untilPrice=&PriceType=1&FromFloor=&ToFloor=&EnterDate=&Info=';

xray(URL)
  .use(phantom())
  .select([{
    $root: 'body',
    tds: ['td']
  }])
  .run(function(error, scraped) {
    console.log(scraped);
});
```

**Comment by YonathanB** [comment]
Yes I tried it. It's working fine.
I just have some problem for clicking on tds via the crawler, but I'll post it as a new issue in 'x-ray-phantom'.
Thanks again :+1:

**Comment by MatthewMueller** [comment]
`<td>`'s are not programmatically clickable iirc

**Comment by YonathanB** [comment]
Even if there is an 'onclick' event on them?

**Comment by MatthewMueller** [comment]
not sure, I'd try generating a click event yourself in the console to see:

https://github.com/segmentio/nightmare/blob/master/lib/actions.js#L190-L193

before you go down a rabbit hole.

**Comment by YonathanB** [comment]
Well, I tried the following:
<table>
    <tr >
        <td onclick="console.log('Hello')">click me</td>
    </tr>
</table>

And it's working

**Comment by matthewmueller** [comment]
Removed this example entirely
