### ISSUE TITLE
Example using regular expressions

### ISSUE THREAD

**Issue by ivansabik** [lapwinglabs/x-ray#26]
Hi, I am wondering if you could help me figure out if regex is supported and if so how to use them. So far I've tried with this URL http://www.finanzas.df.gob.mx/sma/detallePlaca.php?placa=183YTP:

```
var xray = require('..');
var url = 'http://www.finanzas.df.gob.mx/sma/detallePlaca.php?placa=183YTP';
xray(url)
  .select([{
      $root: '#tablaDatos',
      folio: new RegExp(/./)
  }])
  .run(function(err, infraccion) {
    console.log(infraccion);
  });
```

also

```
var xray = require('..');
var url = 'http://www.finanzas.df.gob.mx/sma/detallePlaca.php?placa=183YTP';
xray(url)
  .select([{
      $root: '#tablaDatos',
      folio: /./
  }])
  .run(function(err, infraccion) {
    console.log(infraccion);
  });
```

But still getting nothing :(

**Comment by ivansabik** [comment]
Got confused with https://www.npmjs.com/package/xray, sorry for that. Would be a nice feature though :D

**Comment by MatthewMueller** [comment]
haha oh man, that is a bit confusing. Yah, that'd be sweet though, cheerio doesn't support regexp matching expressions (nor does jQuery really), so it'd be tough to implement here.
