### ISSUE TITLE
1.0.0

### ISSUE THREAD

**Issue by matthewmueller** [lapwinglabs/x-ray#28]
This issue will be used to track the changes that are coming to X-ray. 

####  More spider, less worm

Right now x-ray can paginate, but it's very limited. It's meant for things like paging through Google results, Dribbble results, etc, where the templates are the same but with different data. 

We want to allow x-ray to crawl multiple different pages simultaneously and join all the data together seamlessly. 

#### Do not limit the power of powerful drivers

Right now the current x-ray severely limits the capabilities of drivers like Segment's phantom driver, nightmare. You can run nightmare up front, but then after you start paginating, you cannot run anymore nightmare scripts. Nightmare scripts should just work in X-ray or at least be easy to add to x-ray

#### Xray instance per page

Each page should initialize a new x-ray instance. X-ray instances are like nodes in a graph. There will need to be some high-level manager to deal with things like concurrency, rate-limiting, and throttling.

---

Interested in hearing your thoughts. Now's the time to chime in with you're use cases, wishes and ideas.

**Comment by jonathanpease** [comment]
It would be great to have a feature that generates a list of URLs to crawl based on specified URL parameters. This crawl strategy is useful for sites that don't paginate but do have predictable url parameters and path patterns.

**Comment by darsain** [comment]
I'd love to have an API for intermediate pages. For example, I wanted to download all of the radiolab  episodes from `http://www.radiolab.org/archive/`, which links to pages about episodes, not directly `.mp3` files.

I imagined something like:

```js
xray('http://www.radiolab.org/archive/')
  .intermediate(['.story-box li a.read-more[href]'])
  .select([.article-audioplayer a.Download.button[href]])
  .write('urls.json');
```

where `.intermediate()` would be chainable if there is more jumps between list and desired content.

That would be so awesome! :)

**Comment by MatthewMueller** [comment]
Thanks guys for the feedback! I've written up some comments on where I think this is heading. Let me know if you have any additional thoughts.

**Comment by matthewmueller** [comment]
The new API has been published. It's all around simpler, supports crawling and has better selector support. 

Some things I'd like to see get added:

- `before(fn)`: Like mocha, run a function before scraping (like logging in, redirecting, etc)
- `after(fn)`: Like mocha, run a function after scraping (like logging out, clearing cookies, etc.)
- `format(formatter, fn)`: This was in the previous API, just need to add it back in.
