### ISSUE TITLE
first example with a[href] weird values

### ISSUE THREAD

**Issue by jeromedecoster** [lapwinglabs/x-ray#29]
Hi,

I just try your first example on `github.com/stars/matthewmueller` 

It seems getting `a[href]` value return weird values starting with `null//null/`

```js
xray('github.com/stars/matthewmueller')
  .select([{
    $root: '.repo-list-item',
    link: '.repo-list-name a[href]'
  }])
  .run(function(err, data) {
    console.log(data)
  })
```

output:

```
[ { link: 'null//null/lapwinglabs/static' },
  { link: 'null//null/EvanMarkHopkins/duo-jsx' },
  { link: 'null//null/google/bazel' },
  ...
```

**Comment by MatthewMueller** [comment]
@jeromedecoster looks like you're missing the `https://` on `https://github.com/stars/matthewmueller`.

It should look something like:

```js
xray('https://github.com/stars/matthewmueller')
  .select([{
    $root: '.repo-list-item',
    link: '.repo-list-name a[href]'
  }])
  .paginate('div.pagination > a:last-child[href]')
  .limit(3)
  .run(function(err, json) {
    if (err) throw err;
    console.log(JSON.stringify(json, true, 2));
  })
```

I've updated the example in the `examples/` directory. Just a heads up though, we're moving towards `1.0.0` and the API will be breaking soon, so if you use x-ray today, make sure to pin it to the minor or patch.

**Comment by jeromedecoster** [comment]
Ok I saw your modification in the example directory.

But I copied the example in the readme.
https://github.com/lapwinglabs/x-ray/blob/master/Readme.md

And it's currently not updated, still have `xray('github.com/stars/matthewmueller')`

**Comment by MatthewMueller** [comment]
Ohh snap, missed the readme one.
