### ISSUE TITLE
formatters should have an `end` function

### ISSUE THREAD

**Issue by matthewmueller** [lapwinglabs/x-ray#3]
Formatter just takes a single function that you can convert JSON objects into RSS, XML, HTML, etc. 

It should also take an end function that's responsible for gluing the array together. 

```js
xray('http://google.com')
  .format(rss())
  .run(function(err, rss) {
    // rss is a feed, not an array of items
  }) 
```

**Comment by olivierlesnicki** [comment]
Would this always run just before the run?

**Comment by MatthewMueller** [comment]
I was thinking about this a bit more last night. I want to support things
like rss and html output formats, so it would need to run after you're done
streaming. I think maybe a transform stream (like the ones in Browserify or
gulp) may be the way to go. Do you have any thoughts? I'm thinking about it
from an API perspective to try and keep .format(rss())

**Comment by olivierlesnicki** [comment]
I like it that way. Great idea.

**Comment by matthewmueller** [comment]
I'm now thinking this should just be done outside of x-ray. `format` has been removed.
