### ISSUE TITLE
.filter and .map methods ?

### ISSUE THREAD

**Issue by jeromedecoster** [lapwinglabs/x-ray#30]
Hi,

What about `.filter` and `.map` methods to manipulate resulted datas?

Your current example

```js
xray('http://mat.io')
  .select(['.Header-list-item a'])
  .run(function(err, array) {
    console.log(array)
    // array is [ 'Github', 'Twitter', 'Lapwing', 'Email' ]
  });
```

With filter

```js
xray('http://mat.io')
  .select(['.Header-list-item a'])
  .filter(function(e) {
    return e.length < 7
  })
  .run(function(err, array) {
    console.log(array)
    // array is [ 'Github', 'Email' ]
  });
```

With map

```js
xray('http://mat.io')
  .select(['.Header-list-item a'])
  .map(function(e) {
    return e + '!'
  })
  .run(function(err, array) {
    console.log(array)
    // array is [ 'Github!', 'Twitter!', 'Lapwing!', 'Email!' ]
  });
```

Useful to manipulate data just before `.write('out.json')`

It can probably be done with `.use(plugin)` but I think this kind of method can be helpful in the builtin version

What do you think?

**Comment by olivierlesnicki** [comment]
Have you tried `.format()` ?

**Comment by jeromedecoster** [comment]
Oh yes, `format` works exactly like `map` with the 3 arguments. Thanks @olivierlesnicki !

```js
.format(function(elm, idx, arr) {
  return elm + '!'
})
```

It was not clear for me because the help only said one argument. But also the name `.format` create confusion. @MatthewMueller perhaps the regular `.map` name is better here?

```js
.format(function(obj) {
  return mustache('<a href="{{link}}">{{title}}</a>', obj);
})
```

I think `filter` can be a good friend for `format || map`

**Comment by olivierlesnicki** [comment]
@jeromedecoster what happens if you don't `return` anything in the `.format` function?
```js
.format(function(elm, idx, arr) {
  if(e.length > 7) {
    return elm + '!'
  }
})
```

**Comment by jeromedecoster** [comment]
Well, your code with `length > 7` returns

```js
xray('http://mat.io')
  .select(['.Header-list-item a'])
  .format(function(elm, idx, arr) {
    if(elm.length > 7) {
      return elm + '!'
    }
  })
  .run(function(err, array) {
    console.log(array)
    // array is [ undefined, undefined, undefined, undefined ]
  });
````

But if you mean filter like my previous example with `length < 7` it still not works like filter

```js
xray('http://mat.io')
  .select(['.Header-list-item a'])
  .format(function(elm, idx, arr) {
    if(elm.length < 7) {
      return elm + '!'
    }
  })
  .run(function(err, array) {
    console.log(array)
    // array is [ 'Github!', undefined, undefined, 'Email!' ]
  });
```

**Comment by olivierlesnicki** [comment]
@jeromedecoster sorry that's what I meant!
filter would be a nice feature

**Comment by olivierlesnicki** [comment]
@jeromedecoster Actually why can't we just do:
xray('http://mat.io')
  .select(['.Header-list-item a'])
  .format(function(elm, idx, arr) {
      return elm + '!'
    }
  })
  .run(function(err, array) {
    console.log(array.filter(function (elm) {
      if(elm.length < 8) {
         return elm;
      }
    });
    // array is [ 'Github!', 'Email!' ]
  });

**Comment by jeromedecoster** [comment]
yes I known but 

```js
xray('http://mat.io')
.select(['.Header-list-item a'])
.fomat(fn)
.run(function(err, arr) {
  arr = arr.filter(fn)
  fs.writeFileSync('out.json', JSON.stringify(arr))
})
```

it's not pretty as below. 

```js
xray('http://mat.io')
.select(['.Header-list-item a'])
.map(fn)
.filter(fn)
.write('out.json');
```

I prefer use the `filter` then `write` method instead of the `run` then `filter` inside `run` then `write` file and `stringify` JSON inside `run`

**Comment by olivierlesnicki** [comment]
@jeromedecoster  Fair point.

**Comment by MatthewMueller** [comment]
I'm +1 to those methods. Just need to make sure it also supports:

```js
xray('http://mat.io')
.select('.Header-list-item a')
.map(fn)
.filter(fn)
.write('out.json');
```

and:

```js
xray('http://mat.io')
.select({ link: '.Header-list-item a' })
.map(fn)
.filter(fn)
.write('out.json');
```

**Comment by matthewmueller** [comment]
This would still be cool to have, I'd accept a PR against 1.0.0 :-)
