### ISSUE TITLE
get innerHTML of selected element

### ISSUE THREAD

**Issue by cyclops24** [lapwinglabs/x-ray#31]
Hi
I need to get innerHTML of selected element in page. Is x-ray can doing thins?? how? I didn't find anything in documentation.

Thanks for your attention.

**Comment by MatthewMueller** [comment]
it's ... `[html]`

**Comment by cyclops24** [comment]
Wooow, Thanks man. It's work.

**Comment by MatthewMueller** [comment]
<3
