### ISSUE TITLE
Saving data to mongodb finished early

### ISSUE THREAD

**Issue by izon90** [lapwinglabs/x-ray#33]
I am trying to scrape some urls and then save them to the mongodb, but it finished early, if I just write out.json it won't end until it finishes. As you can see below after `run()` I save the data to mongodb in a for loop. Why it finished early? The pagination is correct because when I check the out.json, it contains all the data I need.

```
app.get('/crawlAll', function(req, res){
	xray('http://jandan.net/pic')
	  .select([{
	    $root: 'div.row',
	    img: 'div.text p img[src]'
	  }])
	  .paginate('.cp-pagenavi a:last-child[href]')
	  .limit(5)
	  // .write('out.json');
		.run(function(err, imgs){
			res.send(200, imgs);
			for (var i = 0; i < imgs.length; i++) {
				var img = imgs[i].img;
				var newImg = Img({
					url: img
				});
				newImg.save(function(err, success){
					if (success) {
						res.send(200);
					} else {
						res.send(400, err);
					}
				});
			};
		});
});
```

**Comment by matthewmueller** [comment]
Can you try again with the new API, I think this was resolved.

**Comment by mechiles** [comment]
@y0unghe could you share your code? This is of great interest to me in a current project I'm working on.
