### ISSUE TITLE
x-ray with x-ray-select@2.0.0?

### ISSUE THREAD

**Issue by olivierlesnicki** [lapwinglabs/x-ray#36]
Any roadmap for this update?

**Comment by matthewmueller** [comment]
Ah, sorry. I haven't had much time to work on this. Right now, I'm working on x-ray to look more like this: 

https://github.com/rc0x03/node-osmosis/issues/2#issuecomment-89058662

And x-ray-select@2.0.0 will be incorporated into that big re-write. In the meantime though I'd accept a PR to make the current x-ray work with @2x.

**Comment by olivierlesnicki** [comment]
@matthewmueller any branch we can look at for 2.0.0?

**Comment by matthewmueller** [comment]
This is now in master :-)
