### ISSUE TITLE
Send user-agent?

### ISSUE THREAD

**Issue by dilignt** [lapwinglabs/x-ray#4]
Is it possible to send a user-agent header with the xray request?  The site I'm looking at responds with an empty document unless it gets one.

**Comment by MatthewMueller** [comment]
oh yah, i forgot about that. we should add a:

```
xray.ua(...)
```

to x-ray and then it's simple to add to the request driver and phantom driver.

**Comment by andyhu** [comment]
What about using a http proxy?
