### ISSUE TITLE
An href referencing the root of a site produces null//null/rest/of/the/url 

### ISSUE THREAD

**Issue by ssteinerx** [lapwinglabs/x-ray#43]
This link in the HTML:
```				
<div class="promo_img">
	<a href="/product/studley-moms_night_out_bouquet/display">
		<img id="productImageImg_3" 
		src="http://blah/blah/not/important" alt="Studley's Mom's Night Out Bouquet">
	</a>
</div>
```	
Selected with this:

```
  link: '.promo_img a[href]'
```

Gives this:
```
    "link": "null//null/product/studley-moms_night_out_bouquet/display"
```

I'm not sure whether this is an x-ray or x-ray-select issue.

**Comment by matthewmueller** [comment]
Yikes, what was the site? We try to resolve the paths for all the <a> tags so you can crawl further.

**Comment by ssteinerx** [comment]
http://www.studleyflorist.com/

**Comment by matthewmueller** [comment]
New x-ray should fix this!

```js
var xray = require('x-ray')();

xray('http://www.studleyflorist.com/', '.promo_container', [{
  link: '.promo_img a[href]@href'
}])(function(err, arr) {
  if (err) throw err;
  console.log(arr);
})
```

Results in:

```
[ { link: 'http://www.studleyflorist.com/product/studley-country_fresh_mothersday_bouquet/display' },
  { link: 'http://www.studleyflorist.com/product/studley-studleys_english_garden_mothersday-1/display' },
  { link: 'http://www.studleyflorist.com/product/the-ftd-light-of-my-life-bouquet-2012/display' },
  { link: 'http://www.studleyflorist.com/product/the-ftd-all-aglow-bouquet-by-better-homes-and-gardens/display' },
  { link: 'http://www.studleyflorist.com/product/the-ftd-spirit-of-spring-basket-2012/display' },
  { link: 'http://www.studleyflorist.com/product/the-ftd-wonderous-nature-bouquet/display' } ]
```

**Comment by ssteinerx** [comment]
Thanks!  That looks much better.

**Comment by ssteinerx** [comment]
Your exact code, copy & pasted gives this:
xray-failed-attempt.js:26
xray('http://www.studleyflorist.com/', '.promo_container', [{
^
TypeError: object is not a function
    at Object.<anonymous> (/Users/ssteiner/Desktop/meteor/wssw-meteor-packages/studley-scraper/tests/studlys-scraper/xray-failed-attempt.js:26:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by ssteinerx** [comment]
Don't know what the heck happened, but x-ray got uninstalled from the project when I pruned.  Working now.
