### ISSUE TITLE
Authentication? 

### ISSUE THREAD

**Issue by rclai** [lapwinglabs/x-ray#5]
How about login to get cookies before scraping? Maybe at least sending cookies?

**Comment by MatthewMueller** [comment]
I'm not sure about saving cookies, but you should be able to authenticate using the [x-ray phantom driver](https://github.com/lapwinglabs/x-ray-phantom), then scrape the page. 

The phantom driver uses [Nightmare](https://github.com/segmentio/nightmare) which has some information on how to login to a page.

**Comment by MatthewMueller** [comment]
Were you able to get this working?

**Comment by rclai** [comment]
I haven't test this yet. I will let you know.

**Comment by gebrits** [comment]
See #22 for doing authN without needing to use PhantomJS. Thanks to @olivierlesnicki
