### ISSUE TITLE
CSV

### ISSUE THREAD

**Issue by jaggedsoft** [lapwinglabs/x-ray#60]
I LOVE this project more than all others, second only to cheerio, which I love the best.

Is there a simple way to export to CSV? Json can get too big for huge datasets.
Thanks!

**Comment by matthewmueller** [comment]
Thanks, I appreciate the kind words. 

I decided to keep the formatting outside of the project, because there are quite a few other modules that handle the conversion well: https://www.npmjs.com/search?q=json+csv
