### ISSUE TITLE
Named attributes

### ISSUE THREAD

**Issue by itjustwerks** [lapwinglabs/x-ray#7]
Hoping I'm just missing the syntax on this one. I'm trying to scrape a poorly structured site and have to rely on the "align" attribute of some table "td" tags to figure out what is what. In jQuery, I could select 
<code>$('td[align="left"]') or $('td[align="right"]')</code>
to get the correct element. Does anything like that exist in x-ray? I see if I do something like 
<code>tdAlign: ['td[align]']</code>
I get an array of all of those "align" attributes. Is there a way to feed to another function to continue scraping children of elements when the attribute is "left" or "right"? Thanks.

**Comment by itjustwerks** [comment]
Also, is it possible to select the nth occurrence of an element? Again, going back to jQuery, the syntax would be something like
<code>$('td[0]') or $('td[1]')</code>
to specify which zero-based item to choose.

**Comment by MatthewMueller** [comment]
Oh shoot, this is probably conflicting with the selector parser. 

By passing the entire selector to cheerio, it should be able to select only the `td[align]` elements, which is what you want most of the time. Only issue I can see is if you want to query for something like this: 

> "Get me the id of all td elements with the attribute 'align'"

That would probably look something like this in `x-ray`:

```
td[align][id]
```

which may be kind of strange.

**Comment by MatthewMueller** [comment]
A quick way to solve this would be to allow `xray.prepare(...)` to filter out properties if the function  returns `false` or `undefined`. That would look something like this:

```js
xray
  .prepare('align', function(str) {
    return str == 'left' ? str : false;
  })
  .select('td[align] | align')
```

Won't have time to get to this right now, but it'd be an easy PR.

**Comment by itjustwerks** [comment]
Hmmm...I was thinking more along the lines of needing to select child elements or element values based on the value of an attribute. So my use case is

> "Get me the value of all td elements with an align attribute value of 'left'"

I'm not looking for the actual value of the attribute itself. The full jQuery example would be

<code>var myVal = $('td[align="left"]').html();</code>

Here's what I have in x-ray so far

<code>xray('[URL]')
   .select([{
      $root: '#rootDivId',
      title: 'th > span',
      tdStuff: {
         label: ['tr > td[align="left"] > span],
         value: ['tr > td[align="right"] > span]
      }
   }])
   .write(process.stdout);</code>

This would also work if I could specify the array index of the two td elements, but that also doesn't work.

**Comment by cbou** [comment]
I have the same problem with paginate. I would like to use a selector like `a[title="next page"][href]` but it's not possible.

Why not use a syntax which is not conflicting with a css selector like you did for `|` ?

```
a !href
a @href
```

It looks a bit strange and not so common like `a[href]` but it's more powerful.

**Comment by MatthewMueller** [comment]
How does this look: `a[title='next page'][html](text)`

This would select the **text** of `<a title="next page" html>`

**Comment by cbou** [comment]
Yep with `(...)` would works.

But how to select the attribute src **href** of `<a title="next page" html>` ?

Parenthesis are used for `:contains()` and other pseudo selector.

**Comment by MatthewMueller** [comment]
it would look something like:

`a[title='next page'][html](href)`

**Comment by cbou** [comment]
Oh right for **text** I thought you've meant text inside the tag, but you've meant text attribute right?

For `<a title="next page" html href="next.html">Next page</a>`:

`a[title='next page'][html](href)` selects `next.html`
`a[title='next page'][html]` selects `Next page`

**Comment by MatthewMueller** [comment]
yep exactly, default is `(text)` though. So, 

`a[title='next page'][html]` is the same as `a[title='next page'][html](text)`

**Comment by cbou** [comment]
Then you can't select `text` attribute: `<a text="foo">bar</a>`.

I would say `a[title='next page'][html]` and `a[title='next page'][html](text)` should not be the same.

**Comment by olivierlesnicki** [comment]
You do have a faire usage of `()` in css:
`:lang()`
`:nth-child()`
`:nth-of-type`
etc..

**Comment by MatthewMueller** [comment]
right, good call, those can be handled with a list though

**Comment by olivierlesnicki** [comment]
Updating the rselector to this could do it:
`(.+:[^\)]+\)|[^\(]+)?(?:\(([^\(]+)\))?`

**Comment by MatthewMueller** [comment]
+1, if simply updating regex works then I'm all for it.

**Comment by olivierlesnicki** [comment]
I'll write a range of test cases for this today and see if i can find any breaking scenario

**Comment by olivierlesnicki** [comment]
After much investigation I would actually recommend using `{}` instead of `()` to implement this.
The combined list of CSS (`:lang()`, `:nth-child()`, ...) and jQuery (`:eq()`, `:contains()`, ...) selectors means that the use of `()` in CSS shouldn't be consider as an exception but rather as the norm.

Also, how does filters handles `[lang|=en]` which selects all elements with a lang attribute value starting with "en".

**Comment by olivierlesnicki** [comment]
Raised PR https://github.com/lapwinglabs/x-ray-select/pull/6

**Comment by olivierlesnicki** [comment]
Or we could use `->` has the attribute accessor.
`.element->class` instead of `.element[class]` or `.element{class}`.

**Comment by cbou** [comment]
+1 for `->`

**Comment by MatthewMueller** [comment]
Hey guys, please continue the discussion here: https://github.com/lapwinglabs/x-ray-select/pull/7#issuecomment-81335045
