### ISSUE TITLE
Question: Selectors

### ISSUE THREAD

**Issue by tommykennedy** [lapwinglabs/x-ray#74]
I am trying to extract data from Meta Tags and the following snippet returns empty values. 

Any idea on what I am doing wrong?

    var Xray = require('x-ray');
    var x = Xray();

    x('http://www.rte.ie', {
       title: 'title',
       metatags: x('meta', [{
        name: 'meta@name',
        description: 'meta@content'
     }]),
    meta: 'meta'
    })(function (err, obj) {
    console.log(obj);
    })

**Comment by tommykennedy** [comment]
name: '@name' made it work

**Comment by mechiles** [comment]
@tommykennedy what was the fix? I've changed to '@name' but I just get '[Object]' instead of the actual result.

**Comment by reedo808** [comment]
<p>Try changing both '@name' and '@content'.</p>
<pre>
var Xray = require('x-ray');
var x = Xray();

x('http://www.rte.ie', {
   title: 'title',
   metatags: x('meta', [{
    name: '@name',
    description: '@content'
 }]),
meta: 'meta'
})(function (err, obj) {
console.log(obj);
})
</pre>
<p>results would be...</p>
<pre>
{ title: 'RTÉ Ireland\'s National Television and Radio Broadcaster',
  metatags: 
   [ { description: 'IE=edge' },
     { description: '1048256502' },
     { name: 'DC.type', description: 'home' },
     { description: 'text/html; charset=utf-8' },
     { name: 'google-site-verification',
       description: 'SUu_pM4UWy-lboa9HJjcnB08xPJxkKkrlZxo3Q3Spso' },
     { name: 'robots', description: 'noarchive' },
     { name: 'pillar', description: 'Home Page' },
     { name: 'DC.title',
       description: 'RTÉ Ireland\'s National Television and Radio Broadcaster' },
     { name: 'geo.region', description: 'IE-D' },
     { name: 'geo.placename', description: 'Dublin' },
     { name: 'geo.position', description: '53.315605;-6.224404' },
     { name: 'ICBM', description: '53.315605, -6.224404' },
     { name: 'Description',
       description: 'RTÉ news brings you the latest Irish news, world news, international news and up to the minute reports on breaking Irish news stories and news from around the world. Watch and listen to Irish news stories on our video and audio streams.' },
     { name: 'Keywords',
       description: 'irish news breaking news international news current affairs rte television news rte radio news Ireland video audio broadcaster irish ' },
     { name: 'save', description: 'history' } ] }
</pre>

**Comment by mechiles** [comment]
@reedo808 That's what I was trying and still just returns <code>[Object]</code>. Any further help would be much appreciated.

Here's my code:

```
xray('https://news.search.yahoo.com/search?p=sports', '.NewsArticle',
	[{
		title: 'h3.title',
		summarybody: '.compText',
		a: 'a@href',
		cite: '.cite',
		css: '@class',
		 details: xray('a@href', {
	       title: 'h1.headline',
	       body: '.body',
	       metatags: xray('meta', [{
    		name: '@name',
    		description: '@content'
 			}]),
		 meta: 'meta'
	   })
	}]
)(function(err, obj){
if (err) {
    console.error(err);
  }
  console.log("RESULT:", obj);
});
```

Here's a sample result:

```
{ title: 'Reuters Sports Schedule at 0001 GMT on Monday, Oct 5',
    summarybody: 'Reuters sports schedule at 0001 GMT on Monday: - - - - RUGBY WORLD CUP (to 31) No knee-jerk response to England demise, says RFU\'s Ritchie LONDON - England will not rush into hasty decisions over the future of head coach Stuart Lancaster after making their Rugby World Cup exit at the pool stage, says RFU Chief Executive Ian Ritchie. ... ',
    a: 'http://news.yahoo.com/reuters-sports-schedule-0001-gmt-monday-oct-5-000101079--spt.html',
    cite: 'Reuters via Yahoo! News',
    css: 'dd algo NewsArticle',
    details: 
     { title: 'Reuters Sports Schedule at 0001 GMT on Monday, Oct 5',
       body: '*condensed for TL;DR*',
       metatags: [Object] } },
```

**Comment by yusiswtor** [comment]
I think it's an issue with nodejs having problems logging out the objects - I had the same "issue", but when I did a console log of the sub element (in this case console.log(obj.details.metatags);), it gave me the actual element. I never found the root cause (I didnt need that data after all), but at least that gave me a way of reading the data. 

On a sidenote, there is an rss feed reader that can be installed with npm install feedreader which I've found to be easier for keeping track of news feeds.. :) I'm then using x-ray to scrape the actual article.

**Comment by mechiles** [comment]
Thanks @yusiswtor. I thought I was doing it "right". I'll have to look into the feedreader. Sounds like that might normalize the info from multiple sources to scrape accordingly.

**Comment by tomalex0** [comment]
I'm trying to get  meta `name` and `property` attribute details

## This works fine
```
x('http://www.rte.ie', {
   metatags_name: x('meta', [{
    name: '@name',
    description: '@content'
 }]),
metatags_property: x('meta', [{
    name: '@property',
    description: '@content'
 }])
})(function (err, obj) {
console.log(obj);
})
```


## Is this possible ?
```
x('http://www.rte.ie', {
   metatags: x('meta', [{
    name: '@name',
    description: '@content'
 },{
    name: '@property',
    description: '@content'
 }])
})(function (err, obj) {
console.log(obj);
})
```
