### ISSUE TITLE
Select innerHTML

### ISSUE THREAD

**Issue by mukimov** [lapwinglabs/x-ray#8]
As I see it is impossible to get innerHTML from selected node. Any thought about how to implement this feature?

**Comment by vjo** [comment]
You should look at [x-ray-select](https://github.com/lapwinglabs/x-ray-select) which is the module that select node.

x-ray-select, use the jQuery .text() function to select the text inside the node, [view here](https://github.com/lapwinglabs/x-ray-select/blob/master/index.js#L64). As a quick hack, you may want to change that to get the HTML.

**Comment by MatthewMueller** [comment]
You should be able to run `a[html]` to select the innerHTML

**Comment by vjo** [comment]
Hey @MatthewMueller :)

I tried using `a[html]` but it doesn't work.
By reading [x-ray-select source](https://github.com/lapwinglabs/x-ray-select/blob/master/index.js#L64), it will be translated to something like: `$(el).attr('html')` that doesn't select innerHTML.

Maybe I'm missing something?

**Comment by MatthewMueller** [comment]
Arg. I think you're right. Sorry about that. The plan is to support html
that way, must have forgot to implement it. Should be a simple conditional.

**Comment by mukimov** [comment]
@MatthewMueller sounds great, I should be not hard to implement this feature. Thank you!
