### ISSUE TITLE
Delay doesnt work

### ISSUE THREAD

**Issue by kvermeille** [lapwinglabs/x-ray#85]
When creating a request, using delay doesn't delay the request. This can be used for pages that use javascript to load content dynamically.

**Comment by matthewmueller** [comment]
So delay isn't actually for waiting for content to load, for that you'll need to use phantom-x-ray. delay is meant for waiting after a successful scrape, so you don't overdo the scraping on any particular website.

**Comment by kvermeille** [comment]
Ahh ok thanks!!

**Comment by matthewmueller** [comment]
no problems. delay does sound like it would wait for the page to finish, i wonder if there's a better word to describe that.

**Comment by hackerunet** [comment]
Is there any workaround for this? There are some cases when we cannot use Phantom for example, we are using a cloud service that disallow installing extra packages required to use phantom or nightmare for example, so dynamic content is used very often these days, how can I pass the request to xray using a request-x-ray driver for example and force stay still for 1 second before scrapping the content??? thanks.
