### ISSUE TITLE
Confused by the API

### ISSUE THREAD

**Issue by aexmachina** [lapwinglabs/x-ray#89]
Hi there, I don't know if I'm being dense but I really don't understand the selector interface. What I want to do is extract info from each list item. Given the following markup:

```html
<ul class='posts'>
  <li><span class='date'>Today</span><a>Foo</a></li>
  <li><span class='date'>Tomorrow</span><a>Bar</a></li>
</ul>
```

I want to be able to get:

```js
[{date: 'Today', title: 'Foo'}, {date: 'Tomorrow', title: 'Bar'}]
```

I would expect to be able to do something like:

```js
x(url, ['ul.posts li'], {date: '.date', title: 'a'})(function(err, results) {
  console.log('results', results);
});
```

But I can't for the life of me work out how to do this. I can get:

```js
{date: ['Today', 'Tomorrow'], title: ['Foo', 'Bar']}
```

Am I missing something? Just thought I'd give you some feedback because it doesn't make much sense to me.

**Comment by aexmachina** [comment]
FWIW, I think it would be much simpler to select `ul.posts li` and get a result that contains DOM nodes that I can then extract the data out of. That seems much closer to the standard jQuery idiom.

**Comment by sultanshakir** [comment]
@aexmachina check out John's short series on Egghead.io here: https://egghead.io/lessons/node-js-intro-to-web-scraping-with-node-and-x-ray

**Comment by aexmachina** [comment]
Okay, now I understand. In that case, I think the documentation is confusing: `xray(url, scope, selector)` should be `xray(url, selector, schema)`. Thanks.

**Comment by matthewmueller** [comment]
@aexmachina that's not quite right. `scope` and `selector` are from the jQuery work. So something like:

```
xray('a', '@href')
```

translates to:

```
$('a').attr('@href')
```

I'm calling `@href` in this context an **attribute selector**, but this:

```
xray('ul', 'li')
```

Translates to:

```
$('ul').find('li')
```

Where `ul` is the **scope** for the **selector** `li`.

**Comment by aexmachina** [comment]
Yes, that's what I got from the documentation, but it really didn't help me to understand how to do what I wanted. `[{date: 'span', title: 'a'}]` really isn't a selector in any sense that I'm familiar with. The solution to my case was `x(url, 'ul.posts li', [{date: 'span', title: 'a'}])` which is very much `x(url, selector, schema)`.

Anyway, clearly we have a difference of opinion. Just wanted to provide some feedback.

**Comment by matthewmueller** [comment]
For some reason, I interpreted your previous comment as saying there was a typo. Reading it again, I realized that's not what you meant. I'll keep this in mind, thanks!
