### ISSUE TITLE
Support non UTF-8

### ISSUE THREAD

**Issue by cbou** [lapwinglabs/x-ray#9]
It seams that x-ray does not support non UTF-8 yet.

It would be useful to be able to send options to superagent.

**Comment by MatthewMueller** [comment]
+1

**Comment by falkenlabs** [comment]
Hi everyone, 

I have found a trick using [superagent-charset](https://github.com/magicdawn/superagent-charset)

```javascript
var superagent = require('superagent-charset')

module.exports = driver

function driver(enc, opts) {
  var agent = superagent.agent(opts || {})

  return function http_driver(ctx, fn) {
    agent
      .get(ctx.url)
      .charset(enc)
      .set(ctx.headers)
      .end(function(err, res) {
        if (err && !err.status) return fn(err)

        ctx.status = res.status
        ctx.set(res.headers)

        ctx.body = 'application/json' == ctx.type
          ? res.body
          : res.text

        // update the URL if there were redirects
        ctx.url = res.redirects.length
          ? res.redirects.pop()
          : ctx.url

        return fn(null, ctx)
      })
  }
}
```

After that import the driver and use xray.driver function.

```javascript
let request = require('./my-xray-driver');
let Xray = require('x-ray)';
let x = Xray().driver(request('Windows-1252'));
```

What do you think ?

**Comment by jmartsch** [comment]
@falkenlabs This solution is so nice. Helped me a lot. Thank you :)

**Comment by matthewmueller** [comment]
thanks @falkenlabs !

**Comment by rcdiaz** [comment]
superagent.agent is not a function

**Comment by smtx** [comment]
@rcdiaz fix for superagent.agent is not a function error

**const charset = require('superagent-charset');
const request = require('super agent')
var superagent = charset(request);**;

module.exports = driver

function driver(enc, opts) {
  var agent = superagent.agent(opts || {})

  return function http_driver(ctx, fn) {
    agent
      .get(ctx.url)
      .charset(enc)
      .set(ctx.headers)
      .end(function(err, res) {
        if (err && !err.status) return fn(err)

        ctx.status = res.status
        ctx.set(res.headers)

        ctx.body = 'application/json' == ctx.type
          ? res.body
          : res.text

        // update the URL if there were redirects
        ctx.url = res.redirects.length
          ? res.redirects.pop()
          : ctx.url

        return fn(null, ctx)
      })
  }
}

**Comment by mcornella** [comment]
Above code properly formatted:
```javascript
const charset = require('superagent-charset');
const request = require('super agent')
var superagent = charset(request);

module.exports = driver

function driver(enc, opts) {
  var agent = superagent.agent(opts || {})

  return function http_driver(ctx, fn) {
    agent
      .get(ctx.url)
      .charset(enc)
      .set(ctx.headers)
      .end(function(err, res) {
        if (err && !err.status) return fn(err)

        ctx.status = res.status
        ctx.set(res.headers)

        ctx.body = 'application/json' == ctx.type
          ? res.body
          : res.text

        // update the URL if there were redirects
        ctx.url = res.redirects.length
          ? res.redirects.pop()
          : ctx.url

        return fn(null, ctx)
      })
  }
}
```

**Comment by rcdiaz** [comment]
@mcornella @smtx Thanks I will try this in home

**Comment by thebarty** [comment]
OR to do it all in 1 file (this works for me within meteor

```
const Xray = require('x-ray')
const charset = require('superagent-charset')
const request = require('superagent')
const superagent = charset(request)
const utf8Driver = (enc, opts) => {
  var agent = superagent.agent(opts || {})
  return function http_driver(ctx, fn) {
    agent
      .get(ctx.url)
      .charset(enc)
      .set(ctx.headers)
      .end(function(err, res) {
        if (err && !err.status) return fn(err)
        ctx.status = res.status
        ctx.set(res.headers)
        ctx.body = 'application/json' == ctx.type
          ? res.body
          : res.text
        // update the URL if there were redirects
        ctx.url = res.redirects.length
          ? res.redirects.pop()
          : ctx.url
        return fn(null, ctx)
      })
  }
}
const x = Xray().driver(utf8Driver('Windows-1252'))
```

**Comment by thebarty** [comment]
This problem is tougher than I thought.

first of all, I found that using `superagent-charset` a simple call `.charset()` (WITHOUT parameter) will enable automatic parsing.

For me the problem still exists, when trying to scrape different webpages with different charsets.

It is strictly related to the problem of x-ray-crawler https://github.com/matthewmueller/x-ray/issues/183

Any solution out there?
