### ISSUE TITLE
Headers & Request proxy support

### ISSUE THREAD

**Issue by ghost** [lapwinglabs/x-ray#91]
This library has any support for request headers (User-Agent, Cookies, etc) and request proxy?

**Comment by tholu** [comment]
+1

**Comment by anothergituser** [comment]
Easiest way i could find to add a custom UA is to find the file http-driver.js and add something like
`.set('User-Agent', 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36')`
before the `end` function in `http_driver`

**Comment by gebrits** [comment]
May I suggest doing it in the driver as @anothergituser points out, but instead create your own driver (copy/paste from `http-driver.js`) add your needed changes, and reference your own driver using `x.driver(yourVeryOwnDriver)`

**Comment by Kikobeats** [comment]
I close this issue in favour of https://github.com/lapwinglabs/x-ray/issues/51 and https://github.com/lapwinglabs/x-ray/issues/1
